### ISSUE TITLE
tox: pypy tests fail

### ISSUE THREAD

**Issue by heuer** [heuer/segno#80]
```
Traceback (most recent call last):
  File ".tox/pypy/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File ".tox/pypy/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File ".tox/pypy/site-packages/pip/_internal/commands/install.py", line 421, in run
    pycompile=options.compile,
  File ".tox/pypy/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File ".tox/pypy/site-packages/pip/_internal/req/req_install.py", line 831, in install
    requested=self.user_supplied,
  File ".tox/pypy/site-packages/pip/_internal/operations/install/wheel.py", line 829, in install_wheel
    requested=requested,
  File ".tox/pypy/site-packages/pip/_internal/operations/install/wheel.py", line 703, in _install_wheel
    assert os.path.exists(pyc_path)
AssertionError
```

Maybe pip 20.2 is the cause of the problem?
Works for pypy3 and py2.7

**Comment by heuer** [comment]
Seems to be a pip issue with pypy2

```
$ cd .tox/pypy
$ source ./bin/activate
$ pip --version
20.2
$ pip install segno 
$ # ---> Assertion error
$ pip uninstall pip
$ easy_install pip==19.3.1
$ pip install segno
$ # --> Success
```
```
$ pypy --version
Python 2.7.13 (7.0.0+dfsg-3, Mar 24 2019, 15:30:18)
[PyPy 7.0.0 with GCC 8.3.0]
```

**Comment by heuer** [comment]
See also https://github.com/pypa/pip/issues/8653

**Comment by heuer** [comment]
Switched to nox in 5addf2c and provided a workaround. 
Since pypa closed the issue 8653 today no further developments are expected.
